### ISSUE TITLE
Duplication issue with trade and full inventory

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/TradeMe#1]
Hello, we have discovered a duplication issue that occurs on all versions (1.8, 1.13). It's a bit complicated to understand, we managed to reproduce the bug following these steps:

- Requires two players
- Filling a player's full trade inventory
- The other spam the button to accept the trade
- The person with the complete trade inventory leaves the trade during the trade.
_At this point, one player is in the trade phase and the other is not._
- The person who left goes into a chest or open an interface such a shulkerbox...
- The other, still trading, adds resources that the other can retrieve from the chest/interface. 
_The non-trading player needs to disconnect or he can't trade with other players._

When the bug is produced, it generates an exception in the console: https://pastebin.com/ivSdR3UK

I was able to reproduce this bug with a version 1.15.2, it creates an exception in the console each time I try to retrieve them but can take items:
```
>.... [14:12:11 WARN]: [TradeMe] Task #370465 for TradeMe v6.0.3.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: null
```

When the bug is produced, it generates a new exception : https://pastebin.com/H7ruPpGY

Player 1: https://i.imgur.com/HSUIZGU.png
Player 2: https://i.imgur.com/fZQjXLG.png

I'm sorry, I don't know exactly where to send you this issue, I don't think this is the best place given the visibility...

Trade Version :
v6.0.3.2
Server Type (Spigot/Paperspigot/etc):
Paperspigot
Server Version (using /ver):
1.8/1.12/1.15.2

**Comment by Zrips** [comment]
This will be fixed with today's update.

**Comment by AerWyn81** [comment]
Hi, I just tried the latest version. There always seems to be an issue. When one player leaves the trade (ESC key for example), the other still has access to the interface. I have to disconnect the accounts because they are in a phase of infinite trading (can't execute command while trading).

https://i.imgur.com/txLQc8a.png

And when I leave the trade like that, the items that were traded are not returned.

**Comment by Zrips** [comment]
TradeMe6.0.3.4 ? Or .3? As i have posted new version shortly after that update, but 3 people downloaded it, so maybe you got somewhat out of date version which had this issue as it was test code which I forgot to remove.

**Comment by AerWyn81** [comment]
Ah sorry! The issue seems to have been solved. Thanks for everything :)
