### ISSUE TITLE
Dupe potion bug 

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TradeMe#13]
Hello, I'd like to report the dupe potion bug. When you drink the potion at the moment when someone else accepts your trade request, it gets dupped. https://streamable.com/nya6v5

It can work with other consumable items, as well. Can you please fix it?

**Comment by bobhenl** [comment]
Bump? @Zrips https://github.com/Zrips/TradeMe/issues/12 Also may check this please

**Comment by mrfloris** [comment]
> Bump? @Zrips #12 Also may check this please
That's got nothing to do with this dupe report, please don't draw attention to other tickets by going off topic here.

**Comment by Zrips** [comment]
Will be fixed with next update
