### ISSUE TITLE
ShowNewVersion: false does not work

### ISSUE THREAD

**Issue by Dagrond** [Zrips/TradeMe#17]
I have set the option
```
# Shows if there is available new version on login with trademe.versioncheck permission node
ShowNewVersion: false
```
to false, but new version notification still appears.
![image](https://github.com/Zrips/TradeMe/assets/30177675/a487afcd-e82c-4e33-9af2-feede9970538)

BottledExp has the same issue.

**Comment by Zrips** [comment]
Will fix with next update
