### ISSUE TITLE
Traded items amount message bug

### ISSUE THREAD

**Issue by EkonC** [Zrips/TradeMe#2]
Hi, I'd like to report a bug in TryMe plugin.
It is really similiar to https://github.com/Zrips/CMI/issues/4272 which I found earlier, so make sure to check it out.

So basically when I traded 64 Netherrack to 6uamaer, in the chat it wrote down that the player received Netherrack x 18. The amount of Netherrack in the players inventory before the donation was 18, as you can see in the photo. Player got all 64 Netherracks.
![Snímka obrazovky (56)](https://user-images.githubusercontent.com/62595403/98542311-ff5f4200-2290-11eb-88dc-1cc9c172d055.png)
![Snímka obrazovky (57)](https://user-images.githubusercontent.com/62595403/98542315-01290580-2291-11eb-83e0-f75259941b32.png)

**Comment by Zrips** [comment]
Will be fixed with next build
