### ISSUE TITLE
Block PlayerMovement before opening trade GUI

### ISSUE THREAD

**Issue by Achent007** [Zrips/TradeMe#23]
Plugin version: 6.2.1.5
CMILib version: 1.4.7.16
Server /version: pufferfish-35 (MC: 1.20.2) & purpur-2176 (MC: 1.20.4)

Description : 
When a player send a player request and he is mooving, the trade interface is opened and instantly closed.
There is no error on console or something.

But with the TradeMe 6.2.1.4 version this problem doesn't occur

**Comment by Zrips** [comment]
Will be addressed with next update
