### ISSUE TITLE
A few problems;

### ISSUE THREAD

**Issue by FixYourWork** [Zrips/TradeMe#24]
name: TradeMe
main: me.Zrips.TradeMe.TradeMe
version: 6.2.1.5

main: net.Zrips.CMILib.CMILib
name: CMILib
author: Zrips
version: 1.4.7.16

Server version: 1.8.8

1- If a player issue "/trade alex" and if "alex" is not online the message "The player is not online!" is seen. This message is not configurable.
2- We are not able to configure "/trade" command output. There is a "Command.help.output" section in config but its not enough. It would be really better if we can have the list directly.
3- Command allies, it would be really great if we can have command allies like;
**especially for the commands "accept, deny, toggle, block, offer"
  accept:
    help:
      info: ''
      args: ''
      allies:
	- help2
	- help3
4- Shift - Right Click trade request wont fire if u r in worldguard regions. (**for players, OP just fine**)
5- The command "/trade checkperm" throws errors in console if you use as "/trade checkperm fff" or "/trade checkperm qq"
If you use like that "/trade checkperm ff" there is an output but if u add 1 more "f" it throws error same for "qq" example.
6- "You don't have permission!" this message is not configurable.

**Comment by Zrips** [comment]
1. Some more generic locales like "The player is not online!" will be located at CMILib locale file
2. Output from base /trade command is just a list of commands player has access to. So if player has permission access then command will show up, pagination will be added if its over 7 commands. I think all of it should be customizable in locale or CMILib locale (pagination especially)
3. Alias can be tricky and usually interferes with different plugins causing more issues than it solves. Dedicated plugin to create alias can be used in this instance.
4. Duno about this one, would need more information on what you mean exactly with shift- right click
5. Will be fixed
6. This can be modified in CMILib locale file
