### ISSUE TITLE
Issue on trade

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMe#25]
Helli,

A lot of trade are canceled because player move their mouse when the trade start. (because if you are playing and your friend wait 2-3s to accept the trade, you play, so your mouse is moving before the trade start)
It currently cancel 90% of the trade and player just stop using trade because of this, they always need to wait 1s after the opening of the GUI before putting items in it....

It would be possible to change the system (like block the mouse from moving 1s before the trade)

**Comment by Zrips** [comment]
Will be addressed with next update
