### ISSUE TITLE
Mcmmo exp trade bug

### ISSUE THREAD

**Issue by Silentassassin9** [Zrips/TradeMe#7]
Mcmmo exp is traded between players as every level is equivalent to the first level's exp requirement(1020 exp)

Example:
A level 1 miner(miner#1) is trading with a level 987 miner(miner#2)(both are at their respective levels with no extra exp toward the next level) and gives miner#2 1020 exp toward the miner skill. The TradeMe plugin then sees the total amount of miner exp that is being traded is equivalent to 1 levels and then sets miner#2 to level 988, giving miner#2 almost 19k extra xp

**Comment by Zrips** [comment]
Should be resolved with next version.
