### ISSUE TITLE
Option for disabled to accept or deny command format

### ISSUE THREAD

**Issue by MCLaraTeam** [Zrips/TradeMe#9]
When a request is sent, the user receives a check and a cross in the chat. On some of my servers the players do everything via interface and don't have access to tab any command other than /menu

I would like to request an option to be able to deactivate that users receive the check and the cross.

**Comment by Zrips** [comment]
I can add option to disable accept/decline portion of the message. In case you will want to disable it entirely you will need to set gotOffer in locale file to "" which will disable it entirely. Tho that will prevent from player knowing that someone wants to trade with him, but its a option.
